### ISSUE TITLE
Issues with Google Music : --gmusic-playlist

### ISSUE THREAD

**Issue by juanrubio** [tizonia/tizonia-openmax-il#328]
Playlist error originally reported in #325:
```
[Google Play Music] (KeyError) : 'Playlist not found : Vad Fruttik'
tizonia exiting (OMX_ErrorInsufficientResources).
 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

**Comment by juanrubio** [comment]
OK, I think this works all right now with the latest patches:

```
❯ tizonia --gmusic-playlist 'Vad Fruttik'
tizonia 0.7.0. Copyright (C) 2017 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Google Play Music] [Connecting] : 'jarubio2001@gmail.com'.
[Google Play Music] [Authenticating] : 'with cached auth token'
[Google Play Music] [Retrieving library] : 'jarubio2001@gmail.com'. 
[Google Play Music] [Playlist] 'Thumbs Up'.
[Google Play Music] [Playlist] 'My Top Songs'.
[Google Play Music] [Playlist] 'test playlist juan'.
[Google Play Music] [Playlist] 'Best Pop of 2013'.
[Google Play Music] [Playlist] 'Best New Metal'.
[Google Play Music] [Playlist] 'Best of 2015'.
[Google Play Music] [Playlist] 'Heavy Metal & Hard Rock: Top Novedades'.
[Google Play Music] [Playlist] 'Best of the Best Rock'.
[Google Play Music] [Playlist] 'Concierto cadena 100 2017'.
[Google Play Music] [Playlist] 'Vad fruttik'.
[Google Play Music] Playing 'Vad fruttik'.
[Google Play Music] [Tracks in queue] '72'.
[Google Play Music] [Connected] : 'jarubio2001@gmail.com'.
[Google Play Music] [Connected] : 'jarubio2001@gmail.com'.
   Vad Fruttik : Beke Presszo
     Album : Fenystopposok
     Year : 2010
     Duration : 3m:20s
     Track : 12
     Audio Stream : 320 kbit/s, 44100 Hz
     MPEG Layer : III, w/o CRC
     Mode : LR stereo, no emphasis
     2 Ch, 44.1 KHz, 16:s:b 
```

**Comment by juanrubio** [comment]
@zolij I'm closing this issue now. If you have a chance try it from source, let me if it works for you. Otherwise, I'm planning to release a new version of Tizonia in the next 2-3 weeks.

**Comment by zolij** [comment]
Hello,

unfortunately it seems the problem is still exists in v0.9.

`[Google Play Music] (KeyError) : 'Playlist not found or found empty : Vad fruttik'

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]`

Additional info: I upgraded system packages and gmusicapi soundcloud pafy youtube-dl python packages. This playlist is created by me.

**Comment by tizonia** [comment]
I see.


Could you please try this command and paste here the full output (this will enable gmusic DEBUG logging on  the console):

```
$ TIZONIA_GMUSICPROXY_DEBUG=1 tizonia --gmusic-playlist "Vad fruttik"
```

**Comment by zolij** [comment]
sorry for the late answer, the output:

> INFO:root:Artist : Elvis Presley
> INFO:root:   Album : All Songs
> INFO:root:   Album : A Touch Of Platinum
> INFO:root:   Album : Elvis Inspirational
> INFO:root:Artist : Los Lonely Boys
> INFO:root:   Album : All Songs
> INFO:root:   Album : Sacred
> INFO:root:   Album : Los Lonely Boys
> INFO:root:Artist : Rise Against
> INFO:root:   Album : All Songs
> INFO:root:   Album : Endgame
> INFO:root:Artist : Heart
> INFO:root:   Album : All Songs
> INFO:root:   Album : Playlist: The Very Best Of Heart
> INFO:root:Artist : Three Days Grace
> INFO:root:   Album : All Songs
> INFO:root:   Album : Rock (Hip Cuts)
> INFO:root:   Album : Never Too Late
> INFO:root:Artist : Shakira
> INFO:root:   Album : All Songs
> INFO:root:   Album : Latin Mix USA
> INFO:root:   Album : Pies Descalzos
> INFO:root:Artist : Lit
> INFO:root:   Album : All Songs
> INFO:root:   Album : A Place In The Sun
> INFO:root:Artist : Five For Fighting
> INFO:root:   Album : All Songs
> INFO:root:   Album : Songs From Dawson's Creek - Vol. II
> INFO:root:   Album : Live
> INFO:root:Artist : The Greyboy Allstars
> INFO:root:   Album : All Songs
> INFO:root:   Album : What Happened To Television?
> INFO:root:Artist : The Romantics
> INFO:root:   Album : All Songs
> INFO:root:   Album : What I Like About You (Digital 45)
> INFO:root:Artist : Cheap Trick
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Hits Of........
> INFO:root:   Album : Cheap Trick At Budokan: The Complete Concert
> INFO:root:Artist : New Kids On The Block
> INFO:root:   Album : All Songs
> INFO:root:   Album : No More Games/The Remix Album
> INFO:root:Artist : Mandy Moore
> INFO:root:   Album : All Songs
> INFO:root:   Album : Mandy Moore
> INFO:root:   Album : Coverage
> INFO:root:Artist : Spin Doctors
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Biggest Loser-Music From The Television Show
> INFO:root:Artist : Weird Al Yankovic
> INFO:root:   Album : All Songs
> INFO:root:   Album : Permanent Record: Al In The Box
> INFO:root:   Album : Greatest Hits
> INFO:root:   Album : Polka Party
> INFO:root:   Album : Transformers
> INFO:root:Artist : CeU
> INFO:root:   Album : All Songs
> INFO:root:   Album : Vagarosa
> INFO:root:Artist : Tito Puente
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Essential Tito Puente
> INFO:root:Artist : David Cook
> INFO:root:   Album : All Songs
> INFO:root:   Album : David Cook
> INFO:root:Artist : Expose
> INFO:root:   Album : All Songs
> INFO:root:   Album : Dance Vault Remixes
> INFO:root:Artist : Maria Matto
> INFO:root:   Album : All Songs
> INFO:root:   Album : Detras Del Amor
> INFO:root:Artist : Sara Bareilles
> INFO:root:   Album : All Songs
> INFO:root:   Album : Love Song
> INFO:root:   Album : Little Voice
> INFO:root:Artist : Janis Joplin
> INFO:root:   Album : All Songs
> INFO:root:   Album : Cheap Thrills/I Got Dem 'Ol Kozmic Blues Again Mama!/Pearl (3 Pak Longbox)
> INFO:root:Artist : Rachael Yamagata
> INFO:root:   Album : All Songs
> INFO:root:   Album : Contemporary Christmas
> INFO:root:Artist : Augustana
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Hills-The Soundtrack
> INFO:root:Artist : Good Charlotte
> INFO:root:   Album : All Songs
> INFO:root:   Album : Good Charlotte: The Live Lounge Performances
> INFO:root:   Album : The Anthem
> INFO:root:Artist : John Mayer
> INFO:root:   Album : All Songs
> INFO:root:   Album : Room For Squares
> INFO:root:Artist : Jessica Simpson
> INFO:root:   Album : All Songs
> INFO:root:   Album : This Is The Remix
> INFO:root:Artist : Umphrey's McGee
> INFO:root:   Album : All Songs
> INFO:root:   Album : Safety In Numbers
> INFO:root:Artist : Etran Finatawa
> INFO:root:   Album : All Songs
> INFO:root:   Album : Tarkat Tajje / Let's Go!
> INFO:root:Artist : Vieux Farka Toure
> INFO:root:   Album : All Songs
> INFO:root:   Album : Fondo
> INFO:root:Artist : Incubus
> INFO:root:   Album : All Songs
> INFO:root:   Album : Live At Lollapalooza 2003
> INFO:root:   Album : When Incubus Attacks, Vol. 1
> INFO:root:Artist : The Fifth Dimension
> INFO:root:   Album : All Songs
> INFO:root:   Album : Ultimate 5th Dimension
> INFO:root:Artist : Ali Spagnola
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Ego
> INFO:root:Artist : Bay City Rollers
> INFO:root:   Album : All Songs
> INFO:root:   Album : Collections
> INFO:root:Artist : Blue Oyster Cult
> INFO:root:   Album : All Songs
> INFO:root:   Album : Some Enchanted Evening
> INFO:root:   Album : Workshop Of The Telescopes:  The Best Of Blue Oyster Cult
> INFO:root:Artist : The Byrds
> INFO:root:   Album : All Songs
> INFO:root:   Album : There Is A Season
> INFO:root:Artist : David Cassidy & The Partridge Family
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Definitive Collection
> INFO:root:Artist : Little Richard
> INFO:root:   Album : All Songs
> INFO:root:   Album : Little Richard's Greatest Hits (Recorded Live)
> INFO:root:Artist : Deniece Williams
> INFO:root:   Album : All Songs
> INFO:root:   Album : 80's Pop Hits
> INFO:root:Artist : Blood, Sweat & Tears
> INFO:root:   Album : All Songs
> INFO:root:   Album : 60's Greatest Hits
> INFO:root:   Album : Super Hits
> INFO:root:Artist : Spanish Harlem Orchestra
> INFO:root:   Album : All Songs
> INFO:root:   Album : United We Swing
> INFO:root:Artist : Miguelito
> INFO:root:   Album : All Songs
> INFO:root:   Album : Oh Yeah
> INFO:root:Artist : Mariah Carey
> INFO:root:   Album : All Songs
> INFO:root:   Album : All I Want For Christmas
> INFO:root:Artist : Jeff Buckley
> INFO:root:   Album : All Songs
> INFO:root:   Album : Grace
> INFO:root:   Album : The Grace EPs
> INFO:root:Artist : Santana
> INFO:root:   Album : All Songs
> INFO:root:   Album : Ultimate Santana
> INFO:root:Artist : Harold Faltermeyer, Steve Stevens
> INFO:root:   Album : All Songs
> INFO:root:   Album : Top Gun - From The Motion Picture Soundtrack
> INFO:root:Artist : The Rascals
> INFO:root:   Album : All Songs
> INFO:root:   Album : A Bronx Tale - Music From The Motion Picture
> INFO:root:Artist : Hanggai
> INFO:root:   Album : All Songs
> INFO:root:   Album : Introducing Hanggai
> INFO:root:Artist : Debashish Bhattacharya
> INFO:root:   Album : All Songs
> INFO:root:   Album : Calcutta Chronicles: Indian Slide-Guitar Odyssey
> INFO:root:Artist : Tea Leaf Green
> INFO:root:   Album : All Songs
> INFO:root:   Album : Radio Tragedy!
> INFO:root:Artist : Train
> INFO:root:   Album : All Songs
> INFO:root:   Album : Alive At Last
> INFO:root:Artist : Kansas
> INFO:root:   Album : All Songs
> INFO:root:   Album : Kansas
> INFO:root:Artist : Two Steps from Hell
> INFO:root:   Album : All Songs
> INFO:root:   Album : SkyWorld
> INFO:root:Artist : Living Colour
> INFO:root:   Album : All Songs
> INFO:root:   Album : Vivid
> INFO:root:Artist : Marc Anthony
> INFO:root:   Album : All Songs
> INFO:root:   Album : Mended
> INFO:root:Artist : Fiona Apple
> INFO:root:   Album : All Songs
> INFO:root:   Album : Pleasantville -Music From The Motion Picture
> INFO:root:Artist : Kelly Clarkson
> INFO:root:   Album : All Songs
> INFO:root:   Album : My December
> INFO:root:Artist : Sarah McLachlan
> INFO:root:   Album : All Songs
> INFO:root:   Album : Afterglow Live
> INFO:root:Artist : KeeMo
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : The Black Keys
> INFO:root:   Album : All Songs
> INFO:root:   Album : Lonely Boy
> INFO:root:Artist : Martin Solveig
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Vinylshakerz
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Tim Berg
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Naksi
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Tikos Groove
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Mike Candys
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Kaukazus
> INFO:root:   Album : All Songs
> INFO:root:   Album : Amerika nem hazudik
> INFO:root:Artist : Kispal es a Borz
> INFO:root:   Album : All Songs
> INFO:root:   Album : Napozz Holddal (Bucsukoncert)
> INFO:root:Artist : Dj Antoine
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : ATB
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Riva Starr
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Michael Gray
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Joe K
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Jerry Ropero
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Nadia Ali
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Metro Station
> INFO:root:   Album : All Songs
> INFO:root:   Album : Metro Station
> INFO:root:   Album : Shake It (Remixes)
> INFO:root:Artist : Alice Cooper
> INFO:root:   Album : All Songs
> INFO:root:   Album : Alice Cooper Classicks
> INFO:root:Artist : Stereo Palma
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Men at Work
> INFO:root:   Album : All Songs
> INFO:root:   Album : NOW That's What I Call The '80s
> INFO:root:Artist : Crossfade
> INFO:root:   Album : All Songs
> INFO:root:   Album : Crossfade
> INFO:root:Artist : Andra
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : London Grammar
> INFO:root:   Album : All Songs
> INFO:root:   Album : If You Wait (Deluxe Version)
> INFO:root:Artist : Gigi D'Agostino
> INFO:root:   Album : All Songs
> INFO:root:   Album : L'amour toujours - Chanson for the heart
> INFO:root:   Album : L'amour toujours - Beats for the feet
> INFO:root:Artist : Emil Lassaria
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Europe
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Final Countdown
> INFO:root:Artist : Alvin es a Mokusok
> INFO:root:   Album : All Songs
> INFO:root:   Album : A Bolcsek Meg Hallgattak
> INFO:root:Artist : Cyndi Lauper
> INFO:root:   Album : All Songs
> INFO:root:   Album : Twelve Deadly Cyns...And Then Some
> INFO:root:Artist : Disclosure
> INFO:root:   Album : All Songs
> INFO:root:   Album : If You Wait (Deluxe Version)
> INFO:root:Artist : Bonnie Tyler
> INFO:root:   Album : All Songs
> INFO:root:   Album : Secret Dreams And Forbidden Fire
> DEBUG:gmusicapi.Mobileclient1:ListPlaylists(args=[], kwargs={'start_token': None, u'max_results': 20000})
> DEBUG:urllib3.connectionpool:https://mclients.googleapis.com:443 "POST /sj/v2.5/playlistfeed?tier=fr&hl=en_US&include-tracks=true&dv=0&alt=json&updated-min=-1 HTTP/1.1" 200 None
> DEBUG:gmusicapi.Mobileclient1:{u'kind': u'sj#playlistList', u'data': {u'items': [u'<11 playlists>']}}
> DEBUG:gmusicapi.Mobileclient1:ListPlaylistEntries(args=[], kwargs={'start_token': None, u'max_results': 20000, 'updated_after': None})
> DEBUG:urllib3.connectionpool:https://mclients.googleapis.com:443 "POST /sj/v2.5/plentryfeed?tier=fr&hl=en_US&include-tracks=true&dv=0&alt=json&updated-min=-1 HTTP/1.1" 200 None
> DEBUG:gmusicapi.Mobileclient1:{u'nextPageToken': u'MhYKCwoAKLDs/MOjz7wCEJXv9aKLnM8C', u'kind': u'sj#playlistEntryList', u'data': {u'items': [u'<146 plentries>']}}
> DEBUG:gmusicapi.Mobileclient1:ListPlaylistEntries(args=[], kwargs={'start_token': u'MhYKCwoAKLDs/MOjz7wCEJXv9aKLnM8C', u'max_results': 20000, 'updated_after': None})
> DEBUG:urllib3.connectionpool:https://mclients.googleapis.com:443 "POST /sj/v2.5/plentryfeed?tier=fr&hl=en_US&include-tracks=true&dv=0&alt=json&updated-min=-1 HTTP/1.1" 200 None
> DEBUG:gmusicapi.Mobileclient1:{u'kind': u'sj#playlistEntryList', u'data': {u'items': [u'<423 plentries>']}}
> INFO:root:playlist name : 2013. oktober 20. varolista
> [Google Play Music] (KeyError) : 'Playlist not found or found empty : Vad fruttik'
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/tizgmusicproxy.py", line 463, in enqueue_playlist
>     raise KeyError("Playlist not found or found empty : {0}".format(arg))
> KeyError: 'Playlist not found or found empty : Vad fruttik'
> 
> tizonia exiting (OMX_ErrorInsufficientResources).
> 
>  [OMX.Aratelia.audio_source.http:port:0]
>  [OMX_ErrorInsufficientResources]

**Comment by tizonia** [comment]
I apologize for the long wait. 

I think I may have a fix in this commit d986b0b

Would you be a able to test it?

**Comment by juanrubio** [comment]
I believe this is fixed so I'm closing for now.

v0.10.0 binaries will be available from tonight, and we will re-open if necessary.

**Comment by zolij** [comment]
For some reason I couldn't build from source but I will test it when release will come out.

**Comment by zolij** [comment]
Hi,

unfortunatly v0.10.0 still not fix the issue (but at least it doesn't break console at this error :))

debug output (the funny things that's the playlist actually there as previous item):

> INFO:root:Artist : Elvis Presley
> INFO:root:   Album : All Songs
> INFO:root:   Album : A Touch Of Platinum
> INFO:root:   Album : Elvis Inspirational
> INFO:root:Artist : Los Lonely Boys
> INFO:root:   Album : All Songs
> INFO:root:   Album : Sacred
> INFO:root:   Album : Los Lonely Boys
> INFO:root:Artist : Rise Against
> INFO:root:   Album : All Songs
> INFO:root:   Album : Endgame
> INFO:root:Artist : Heart
> INFO:root:   Album : All Songs
> INFO:root:   Album : Playlist: The Very Best Of Heart
> INFO:root:Artist : Three Days Grace
> INFO:root:   Album : All Songs
> INFO:root:   Album : Rock (Hip Cuts)
> INFO:root:   Album : Never Too Late
> INFO:root:Artist : Shakira
> INFO:root:   Album : All Songs
> INFO:root:   Album : Latin Mix USA
> INFO:root:   Album : Pies Descalzos
> INFO:root:Artist : Lit
> INFO:root:   Album : All Songs
> INFO:root:   Album : A Place In The Sun
> INFO:root:Artist : Five For Fighting
> INFO:root:   Album : All Songs
> INFO:root:   Album : Songs From Dawson's Creek - Vol. II
> INFO:root:   Album : Live
> INFO:root:Artist : The Greyboy Allstars
> INFO:root:   Album : All Songs
> INFO:root:   Album : What Happened To Television?
> INFO:root:Artist : The Romantics
> INFO:root:   Album : All Songs
> INFO:root:   Album : What I Like About You (Digital 45)
> INFO:root:Artist : Cheap Trick
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Hits Of........
> INFO:root:   Album : Cheap Trick At Budokan: The Complete Concert
> INFO:root:Artist : New Kids On The Block
> INFO:root:   Album : All Songs
> INFO:root:   Album : No More Games/The Remix Album
> INFO:root:Artist : Mandy Moore
> INFO:root:   Album : All Songs
> INFO:root:   Album : Mandy Moore
> INFO:root:   Album : Coverage
> INFO:root:Artist : Spin Doctors
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Biggest Loser-Music From The Television Show
> INFO:root:Artist : Weird Al Yankovic
> INFO:root:   Album : All Songs
> INFO:root:   Album : Permanent Record: Al In The Box
> INFO:root:   Album : Greatest Hits
> INFO:root:   Album : Polka Party
> INFO:root:   Album : Transformers
> INFO:root:Artist : CeU
> INFO:root:   Album : All Songs
> INFO:root:   Album : Vagarosa
> INFO:root:Artist : Tito Puente
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Essential Tito Puente
> INFO:root:Artist : David Cook
> INFO:root:   Album : All Songs
> INFO:root:   Album : David Cook
> INFO:root:Artist : Expose
> INFO:root:   Album : All Songs
> INFO:root:   Album : Dance Vault Remixes
> INFO:root:Artist : Maria Matto
> INFO:root:   Album : All Songs
> INFO:root:   Album : Detras Del Amor
> INFO:root:Artist : Sara Bareilles
> INFO:root:   Album : All Songs
> INFO:root:   Album : Love Song
> INFO:root:   Album : Little Voice
> INFO:root:Artist : Janis Joplin
> INFO:root:   Album : All Songs
> INFO:root:   Album : Cheap Thrills/I Got Dem 'Ol Kozmic Blues Again Mama!/Pearl (3 Pak Longbox)
> INFO:root:Artist : Rachael Yamagata
> INFO:root:   Album : All Songs
> INFO:root:   Album : Contemporary Christmas
> INFO:root:Artist : Augustana
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Hills-The Soundtrack
> INFO:root:Artist : Good Charlotte
> INFO:root:   Album : All Songs
> INFO:root:   Album : Good Charlotte: The Live Lounge Performances
> INFO:root:   Album : The Anthem
> INFO:root:Artist : John Mayer
> INFO:root:   Album : All Songs
> INFO:root:   Album : Room For Squares
> INFO:root:Artist : Jessica Simpson
> INFO:root:   Album : All Songs
> INFO:root:   Album : This Is The Remix
> INFO:root:Artist : Umphrey's McGee
> INFO:root:   Album : All Songs
> INFO:root:   Album : Safety In Numbers
> INFO:root:Artist : Etran Finatawa
> INFO:root:   Album : All Songs
> INFO:root:   Album : Tarkat Tajje / Let's Go!
> INFO:root:Artist : Vieux Farka Toure
> INFO:root:   Album : All Songs
> INFO:root:   Album : Fondo
> INFO:root:Artist : Incubus
> INFO:root:   Album : All Songs
> INFO:root:   Album : Live At Lollapalooza 2003
> INFO:root:   Album : When Incubus Attacks, Vol. 1
> INFO:root:Artist : The Fifth Dimension
> INFO:root:   Album : All Songs
> INFO:root:   Album : Ultimate 5th Dimension
> INFO:root:Artist : Ali Spagnola
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Ego
> INFO:root:Artist : Bay City Rollers
> INFO:root:   Album : All Songs
> INFO:root:   Album : Collections
> INFO:root:Artist : Blue Oyster Cult
> INFO:root:   Album : All Songs
> INFO:root:   Album : Some Enchanted Evening
> INFO:root:   Album : Workshop Of The Telescopes:  The Best Of Blue Oyster Cult
> INFO:root:Artist : The Byrds
> INFO:root:   Album : All Songs
> INFO:root:   Album : There Is A Season
> INFO:root:Artist : David Cassidy & The Partridge Family
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Definitive Collection
> INFO:root:Artist : Little Richard
> INFO:root:   Album : All Songs
> INFO:root:   Album : Little Richard's Greatest Hits (Recorded Live)
> INFO:root:Artist : Deniece Williams
> INFO:root:   Album : All Songs
> INFO:root:   Album : 80's Pop Hits
> INFO:root:Artist : Blood, Sweat & Tears
> INFO:root:   Album : All Songs
> INFO:root:   Album : 60's Greatest Hits
> INFO:root:   Album : Super Hits
> INFO:root:Artist : Spanish Harlem Orchestra
> INFO:root:   Album : All Songs
> INFO:root:   Album : United We Swing
> INFO:root:Artist : Miguelito
> INFO:root:   Album : All Songs
> INFO:root:   Album : Oh Yeah
> INFO:root:Artist : Mariah Carey
> INFO:root:   Album : All Songs
> INFO:root:   Album : All I Want For Christmas
> INFO:root:Artist : Jeff Buckley
> INFO:root:   Album : All Songs
> INFO:root:   Album : Grace
> INFO:root:   Album : The Grace EPs
> INFO:root:Artist : Santana
> INFO:root:   Album : All Songs
> INFO:root:   Album : Ultimate Santana
> INFO:root:Artist : Harold Faltermeyer, Steve Stevens
> INFO:root:   Album : All Songs
> INFO:root:   Album : Top Gun - From The Motion Picture Soundtrack
> INFO:root:Artist : The Rascals
> INFO:root:   Album : All Songs
> INFO:root:   Album : A Bronx Tale - Music From The Motion Picture
> INFO:root:Artist : Hanggai
> INFO:root:   Album : All Songs
> INFO:root:   Album : Introducing Hanggai
> INFO:root:Artist : Debashish Bhattacharya
> INFO:root:   Album : All Songs
> INFO:root:   Album : Calcutta Chronicles: Indian Slide-Guitar Odyssey
> INFO:root:Artist : Tea Leaf Green
> INFO:root:   Album : All Songs
> INFO:root:   Album : Radio Tragedy!
> INFO:root:Artist : Train
> INFO:root:   Album : All Songs
> INFO:root:   Album : Alive At Last
> INFO:root:Artist : Kansas
> INFO:root:   Album : All Songs
> INFO:root:   Album : Kansas
> INFO:root:Artist : Two Steps from Hell
> INFO:root:   Album : All Songs
> INFO:root:   Album : SkyWorld
> INFO:root:Artist : Living Colour
> INFO:root:   Album : All Songs
> INFO:root:   Album : Vivid
> INFO:root:Artist : Marc Anthony
> INFO:root:   Album : All Songs
> INFO:root:   Album : Mended
> INFO:root:Artist : Fiona Apple
> INFO:root:   Album : All Songs
> INFO:root:   Album : Pleasantville -Music From The Motion Picture
> INFO:root:Artist : Kelly Clarkson
> INFO:root:   Album : All Songs
> INFO:root:   Album : My December
> INFO:root:Artist : Sarah McLachlan
> INFO:root:   Album : All Songs
> INFO:root:   Album : Afterglow Live
> INFO:root:Artist : KeeMo
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Martin Solveig
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Vinylshakerz
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Tim Berg
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Naksi
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Tikos Groove
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Mike Candys
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Kaukazus
> INFO:root:   Album : All Songs
> INFO:root:   Album : Amerika nem hazudik
> INFO:root:Artist : Kispal es a Borz
> INFO:root:   Album : All Songs
> INFO:root:   Album : Napozz Holddal (Bucsukoncert)
> INFO:root:Artist : Dj Antoine
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : ATB
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Riva Starr
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Michael Gray
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Joe K
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Jerry Ropero
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Nadia Ali
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Metro Station
> INFO:root:   Album : All Songs
> INFO:root:   Album : Metro Station
> INFO:root:   Album : Shake It (Remixes)
> INFO:root:Artist : Alice Cooper
> INFO:root:   Album : All Songs
> INFO:root:   Album : Alice Cooper Classicks
> INFO:root:Artist : Crossfade
> INFO:root:   Album : All Songs
> INFO:root:   Album : Crossfade
> INFO:root:Artist : London Grammar
> INFO:root:   Album : All Songs
> INFO:root:   Album : If You Wait (Deluxe Version)
> INFO:root:Artist : Gigi D'Agostino
> INFO:root:   Album : All Songs
> INFO:root:   Album : L'amour toujours - Beats for the feet
> INFO:root:   Album : L'amour toujours - Chanson for the heart
> INFO:root:Artist : Emil Lassaria
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Disclosure
> INFO:root:   Album : All Songs
> INFO:root:   Album : If You Wait (Deluxe Version)
> INFO:root:Artist : Cyndi Lauper
> INFO:root:   Album : All Songs
> INFO:root:   Album : Twelve Deadly Cyns...And Then Some
> INFO:root:Artist : Europe
> INFO:root:   Album : All Songs
> INFO:root:   Album : The Final Countdown
> INFO:root:Artist : Andra
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : Alvin es a Mokusok
> INFO:root:   Album : All Songs
> INFO:root:   Album : A Bolcsek Meg Hallgattak
> INFO:root:Artist : Stereo Palma
> INFO:root:   Album : All Songs
> INFO:root:   Album : Party Life vol 1
> INFO:root:Artist : The Black Keys
> INFO:root:   Album : All Songs
> INFO:root:   Album : Lonely Boy
> INFO:root:Artist : Men at Work
> INFO:root:   Album : All Songs
> INFO:root:   Album : NOW That's What I Call The '80s
> INFO:root:Artist : Bonnie Tyler
> INFO:root:   Album : All Songs
> INFO:root:   Album : Secret Dreams And Forbidden Fire
> DEBUG:gmusicapi.Mobileclient1:ListPlaylists(args=[], kwargs={'start_token': None, u'max_results': 20000})
> DEBUG:urllib3.connectionpool:https://mclients.googleapis.com:443 "POST /sj/v2.5/playlistfeed?tier=fr&hl=en_US&include-tracks=true&dv=0&alt=json&updated-min=-1 HTTP/1.1" 200 None
> DEBUG:gmusicapi.Mobileclient1:{u'kind': u'sj#playlistList', u'data': {u'items': [u'<10 playlists>']}}
> DEBUG:gmusicapi.Mobileclient1:ListPlaylistEntries(args=[], kwargs={'start_token': None, u'max_results': 20000, 'updated_after': None})
> DEBUG:urllib3.connectionpool:https://mclients.googleapis.com:443 "POST /sj/v2.5/plentryfeed?tier=fr&hl=en_US&include-tracks=true&dv=0&alt=json&updated-min=-1 HTTP/1.1" 200 None
> DEBUG:gmusicapi.Mobileclient1:{u'nextPageToken': u'MhYKCwoAKLDs/MOjz7wCEJXv9aKLnM8C', u'kind': u'sj#playlistEntryList', u'data': {u'items': [u'<146 plentries>']}}
> DEBUG:gmusicapi.Mobileclient1:ListPlaylistEntries(args=[], kwargs={'start_token': u'MhYKCwoAKLDs/MOjz7wCEJXv9aKLnM8C', u'max_results': 20000, 'updated_after': None})
> DEBUG:urllib3.connectionpool:https://mclients.googleapis.com:443 "POST /sj/v2.5/plentryfeed?tier=fr&hl=en_US&include-tracks=true&dv=0&alt=json&updated-min=-1 HTTP/1.1" 200 None
> DEBUG:gmusicapi.Mobileclient1:{u'kind': u'sj#playlistEntryList', u'data': {u'items': [u'<419 plentries>']}}
> INFO:root:playlist name : 2013. oktober 20. varolista
> INFO:root:playlist name : Haza
> INFO:root:playlist name : 2014. november 3. varolista
> INFO:root:playlist name : Relax music
> INFO:root:playlist name : Hans Zimmer Live 2017 Setlist
> INFO:root:playlist name : 2017. aprilis 24. varolista
> INFO:root:playlist name : Greatest Hits Remixed!
> INFO:root:playlist name : Alvas
> INFO:root:playlist name : Vad fruttik
> DEBUG:gmusicapi.Mobileclient1:ListPlaylists(args=[], kwargs={'start_token': None, u'max_results': 20000})
> DEBUG:urllib3.connectionpool:https://mclients.googleapis.com:443 "POST /sj/v2.5/playlistfeed?tier=fr&hl=en_US&include-tracks=true&dv=0&alt=json&updated-min=-1 HTTP/1.1" 200 None
> DEBUG:gmusicapi.Mobileclient1:{u'kind': u'sj#playlistList', u'data': {u'items': [u'<10 playlists>']}}
> [Google Play Music] [Playlist] 'Thumbs Up'.
> [Google Play Music] [Playlist] '2013. oktober 20. varolista'.
> [Google Play Music] [Playlist] 'Haza'.
> [Google Play Music] [Playlist] '2014. november 3. varolista'.
> [Google Play Music] [Playlist] 'Relax music'.
> [Google Play Music] [Playlist] 'Hans Zimmer Live 2017 Setlist'.
> [Google Play Music] [Playlist] '2017. aprilis 24. varolista'.
> [Google Play Music] [Playlist] 'Greatest Hits Remixed!'.
> [Google Play Music] [Playlist] 'Alvas'.
> [Google Play Music] [Playlist] 'Vad fruttik'.
> [Google Play Music] 'Vad fruttik' not found or found empty. Feeling lucky?.
> [Google Play Music] 'Vad fruttik' not found or found empty. Feeling lucky?.
> [Google Play Music] 'Vad fruttik' not found or found empty. Feeling lucky?.
> [Google Play Music] (KeyError) : 'Playlist not found or found empty : Vad fruttik'
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/tizgmusicproxy.py", line 463, in enqueue_playlist
>     raise KeyError("Playlist not found or found empty : {0}".format(arg))
> KeyError: 'Playlist not found or found empty : Vad fruttik'
> 
> tizonia exiting (OMX_ErrorInsufficientResources).
> 
>  [OMX.Aratelia.audio_source.http:port:0]
>  [OMX_ErrorInsufficientResources]
>

**Comment by zolij** [comment]
btw it's not playlist specific, I get this result with my other playlists

**Comment by juanrubio** [comment]
uh... sorry to hear this. Ok, let me look into it again.

**Comment by howardcochran** [comment]
Is there any news about this?  This problem still occurs with the current v0.11 whether installed from APT repository or as a snap package.  The output is just like that posted by zolij on Oct 29, 2017.

**Comment by tizonia** [comment]
I think I may have fixed it in cc715f4.

I might cut a new release later this weekend.
